
CREATE TABLE CORRENTISTA (
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(70) NULL,
    ENDERECO VARCHAR(150)
);
ALTER TABLE CORRENTISTA ADD CONSTRAINT CORRENTISTA_PK PRIMARY KEY (CPF);

CREATE TABLE CONTA (
    NUMERO INTEGER NOT NULL,
    SALDO NUMERIC(15,2) NOT NULL,
    CPF VARCHAR(11) NOT NULL
);
ALTER TABLE CONTA ADD CONSTRAINT CONTA_PK PRIMARY KEY (NUMERO);

CREATE TABLE CARTAO (
    NUMERO INTEGER NOT NULL,
    SENHA VARCHAR(15) NOT NULL,
    EMISSAO DATE NOT NULL,
    LIMITE FLOAT NULL,
    DATA_VALIDADE DATE NOT NULL,
    NUMERO_CONTA INTEGER NOT NULL,
    CPF VARCHAR(11) NOT NULL
);
ALTER TABLE CARTAO ADD CONSTRAINT CARTAO_PK PRIMARY KEY (NUMERO);

#FKs
ALTER TABLE CONTA  ADD CONSTRAINT CORRENTISTA_FK FOREIGN KEY (CPF) REFERENCES CORRENTISTA(CPF);
ALTER TABLE CARTAO ADD CONSTRAINT CORRENTISTA_CARTAO_FK FOREIGN KEY (CPF) REFERENCES CORRENTISTA(CPF);
ALTER TABLE CARTAO ADD CONSTRAINT CONTA_CARTAO_FK FOREIGN KEY (NUMERO_CONTA) REFERENCES CONTA(NUMERO);

